### ISSUE TITLE
SubX: decide on minimal set of syscalls to support

### ISSUE THREAD

**Issue by tekknolagi** [akkartik/mu#10]
https://syscalls.kernelgrok.com/

**Comment by akkartik** [comment]
So far: `exit`, `read`, `write`. Everything is a file, so that should be enough, right? 😛

But seriously we do need at least `open` and `close`. And probably the directory and socket calls.

**Comment by akkartik** [comment]
But we're not going to support them all. Certainly not all the `ioctl()`s.

**Comment by akkartik** [comment]
Draft list:
1. ~`exit`~
2. ~`read`~
3. ~`write`~
4. `open`
5. `close`
6. `creat`
7. `unlink`
8. `rename`

I was going to add socket ones like `bind` and `accept` -- but they aren't syscalls!

**Comment by akkartik** [comment]
Man, it sucks that POSIX is defined in terms of libc. The operating system interfaces defined in terms of a single language's standard library. Such ugly design. The whole thing is lying to generations of programmers.

**Comment by akkartik** [comment]
17. `sbrk`

**Comment by tekknolagi** [comment]
Suggestion: use a checklist instead of an OL. But I like that idea.

**Comment by akkartik** [comment]
https://john-millikin.com/unix-syscalls

via https://news.ycombinator.com/item?id=17706119

**Comment by akkartik** [comment]
Non-socket syscalls are done: https://github.com/akkartik/mu/commit/5cec03b414

**Comment by akkartik** [comment]
This ticket has probably gone as far as it will go. If necessary we'll open another one for socket syscalls at some point.
