### ISSUE TITLE
SubX: Adding labels would improve the programming experience

### ISSUE THREAD

**Issue by tekknolagi** [akkartik/mu#13]
Right now, programmers are left counting bytes. Even a supplemental tool that added byte count annotations to the program would be welcome.

**Comment by tekknolagi** [comment]
How can I be of service -- where would you like this implemented?

**Comment by akkartik** [comment]
Fixed by 6b64f8009b9f98e9008be847ce7d475dc321e7de and 071afeff5d99732b2f50f2a5009dc6f2e8303909.
