### ISSUE TITLE
Typo in mu/opcode

### ISSUE THREAD

**Issue by Epholys** [akkartik/mu#37]
Hello,

I think there is a typo in `mu/opcode` :

opcode:

`0f 86: jump disp8 bytes away if lesser or equal (unsigned), if ZF is set or CF is set (jcc/jbe/jna)` 

should be:

`0f 86: jump disp32 bytes away if lesser or equal (unsigned), if ZF is set or CF is set (jcc/jbe/jna)` 

as every opcode around it. Maybe a missed modification from a copy/paste of opcodes 72 to 7f?

**Comment by akkartik** [comment]
You're right! Thank you very much.
