### ISSUE TITLE
example1:  does not seem to start with default-space or local-scope

### ISSUE THREAD

**Issue by chriscool** [akkartik/mu#4]
I get the above error:

```
> ./mu example1.mu 
example1:  does not seem to start with default-space or local-scope
```

The last commit in the version I use is: 69a321b7f31057b5203e3a63936ed12e34644d65

**Comment by akkartik** [comment]
Ack, thanks for the report. I'll fix in an hour.

**Comment by achikin** [comment]
```
./mu text example1.mu
no such file text
example1:  does not seem to start with default-space or local-scope
```
same commit

**Comment by akkartik** [comment]
Now fixed. Please do a `git pull`.

**Comment by akkartik** [comment]
@achikin: there's also a typo in your command -- should be `test` not `text`.
